### ISSUE TITLE
judgementLink can be broken when anchor has text

### ISSUE THREAD

**Issue by sylmz** [Zeesky-code/CaseExtractorURL#2]
Why do we need to use `print` method?

https://github.com/Zeesky-code/CaseExtractorURL/blob/f4fb2196aaeb9d5b5073eb0abe4ba9bfb552ac34/src/main/java/Scraper.java#L47
Because of the `print` method, all of judgementLinks has extra space char at the end of link.

Can't we use in the following way?

```java
Element link = ruling.select("a[href]").get(0);
String judgementLink = link.attr("abs:href");
```

**Comment by Zeesky-code** [comment]
Removed the extra print and trim methods with https://github.com/Zeesky-code/CaseExtractorURL/commit/8bf2ef6a69fa4688ea278be2c0d3002026797cce
